# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    c1bg.rdu2.centos.org
#BUILDTIME:    Fri Oct  2 09:46:21 2015
#SOURCERPM:    rh-python34-python-six-1.8.0-1.el6.src.rpm

#RPMVERSION:   4.8.0

#INSTALLTIME:  Tue Feb 14 10:35:02 2017

#OS:           linux
#SIZE:           88697
#ARCHIVESIZE:           91376
#ARCH:         noarch
BuildArch:     noarch
Name:          rh-python34-python-six
Version:       1.10.0
Release:       1.el6
License:       MIT 
Group:         Development/Languages
Summary:       Python 2 and 3 compatibility utilities
Distribution:  Centos

URL:           http://pypi.python.org/pypi/six/
Source0:       https://files.pythonhosted.org/packages/source/s/six/six-1.10.0.tar.gz
Vendor:        Centos
Packager:      CBS <cbs@centos.org>
Provides:      rh-python34-python-six = 1.10.0-1.el6
Requires:      rh-python34-python(abi) = 3.4
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PartialHardlinkSets) <= 4.0.4-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
#suggest
#enhance
%description
python-six provides simple utilities for wrapping over differences between
Python 2 and Python 3.

%prep
%setup -q -n six-1.10.0

%build
%{?scl_python:scl enable %{scl_python} "}
%{__python} setup.py build
%{?scl_python:"}

%install
# Explicitly specify --install-purelib %{python_sitelib}, which is now overriden
# to point to vt191, otherwise Python will try to install into the python27
# Software Collection site-packages directory
%{?scl_python:scl enable %{scl_python} "}
%{__python} setup.py install -O1 --skip-build --root %{buildroot} --install-purelib %{python34python3_sitelib}
%{?scl_python:"}

#This is the Python 3 build of the module.
%files
%{python34python3_sitelib}/six*

%changelog
* Tue Feb 14 2017 Marcus Klem <mklemm@arago.de> - 1.10.0-1
- Update to 1.10.0

* Tue Jan 20 2015 Matej Stuchlik <mstuchli@redhat.com> - 1.8.0-1
- Update to 1.8.0

* Wed Nov 13 2013 Tomas Tomecek <ttomecek@redhat.com> - 1.3.0-2
- RHSCL-1.1 build

* Thu Mar 21 2013 David Malcolm <dmalcolm@redhat.com> - 1.3.0-1
- 1.3.0

* Thu Feb 14 2013 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.2.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_19_Mass_Rebuild

* Wed Aug 29 2012 David Malcolm <dmalcolm@redhat.com> - 1.2.0-1
- 1.2.0 (rhbz#852658)
- add %%check section

* Sat Aug 04 2012 David Malcolm <dmalcolm@redhat.com> - 1.1.0-4
- rebuild for https://fedoraproject.org/wiki/Features/Python_3.3

* Sat Jul 21 2012 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.1.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_18_Mass_Rebuild

* Fri Jun 22 2012 Ralph Bean <rbean@redhat.com> - 1.1.0-2
- Conditionalized python3-six, allowing an el6 build.

* Tue Feb 07 2012 David Malcolm <dmalcolm@redhat.com> - 1.1.0-1
- 1.1.0

* Sat Jan 14 2012 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.0.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_17_Mass_Rebuild

* Thu Mar 24 2011 David Malcolm <dmalcolm@redhat.com> - 1.0.0-1
- initial packaging

